### ISSUE TITLE
Go back callback

### ISSUE THREAD

**Issue by afiorenza** [react-native-community/react-native-drawer-layout-polyfill#8]
Hi! great library by the way.

  Is there any way to add a callback on go back arrow?

Thanks

**Comment by DanielMSchmidt** [comment]
Do you mean [onDrawerClose](https://facebook.github.io/react-native/docs/drawerlayoutandroid.html#ondrawerclose)? What is there and what is not can be seen at the official documentation, this is just a polyfill 😇 
https://facebook.github.io/react-native/docs/drawerlayoutandroid.html
